// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Dashboard():Promise<main.Dashboard>;

export function DeleteSite(arg1:string):Promise<void>;

export function ListOpportunities(arg1:main.OpportunityQuery):Promise<Array<main.Opportunity>>;

export function ListSites():Promise<Array<main.SiteConfig>>;

export function ListTasks():Promise<Array<main.CrawlTask>>;

export function RunCrawl(arg1:main.CrawlRequest):Promise<Array<main.CrawlTask>>;

export function SaveRemark(arg1:string,arg2:string):Promise<main.Opportunity>;

export function SaveSite(arg1:main.SiteConfig):Promise<main.SiteConfig>;
