// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dashboard() {
  return window['go']['main']['App']['Dashboard']();
}

export function DeleteSite(arg1) {
  return window['go']['main']['App']['DeleteSite'](arg1);
}

export function GetSchedule() {
  return window['go']['main']['App']['GetSchedule']();
}

export function ListOpportunities(arg1) {
  return window['go']['main']['App']['ListOpportunities'](arg1);
}

export function ListSites() {
  return window['go']['main']['App']['ListSites']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function RunCrawl(arg1) {
  return window['go']['main']['App']['RunCrawl'](arg1);
}

export function SaveSchedule(arg1) {
  return window['go']['main']['App']['SaveSchedule'](arg1);
}

export function SaveSite(arg1) {
  return window['go']['main']['App']['SaveSite'](arg1);
}
