// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearHistory():Promise<main.HistoryClearResult>;

export function Dashboard():Promise<main.Dashboard>;

export function DeleteSite(arg1:string):Promise<void>;

export function GetArchiveConfig():Promise<main.ArchiveConfig>;

export function ListOpportunities(arg1:main.OpportunityQuery):Promise<Array<main.Opportunity>>;

export function ListSites():Promise<Array<main.SiteConfig>>;

export function ListTasks():Promise<Array<main.CrawlTask>>;

export function OpenArchiveDirectory():Promise<void>;

export function RetryArchive(arg1:string):Promise<main.Opportunity>;

export function RunSGCCAutoPages1To7():Promise<Array<main.CrawlTask>>;

export function SaveArchiveConfig(arg1:main.ArchiveConfig):Promise<main.ArchiveConfig>;

export function SaveSite(arg1:main.SiteConfig):Promise<main.SiteConfig>;

export function SelectArchiveDirectory():Promise<string>;
